name: 📊 Report coverage to PR
description: Add the code coverage report to the pull request
inputs:
  coverage-file:
    description: Code coverage file
    required: true
  report-name:
    description: Coverage report heading
    required: true
  comment-header:
    description: Unique sticky comment header
    required: true
runs:
  using: composite
  steps:
    - name: 🔎 Find PR
      id: finder
      uses: jwalton/gh-find-current-pr@v1

    - name: 📊 Create coverage report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.coverage-file }}
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '70 80'

    - name: 📝 Add report heading
      shell: bash
      env:
        REPORT_NAME: ${{ inputs.report-name }}
        COMMENT_HEADER: ${{ inputs.comment-header }}
      run: |
        {
          printf '## %s\n\n' "$REPORT_NAME"
          cat code-coverage-results.md
        } > "$RUNNER_TEMP/code-coverage-results-$COMMENT_HEADER.md"

    - name: 💬 Add coverage PR comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        header: ${{ inputs.comment-header }}
        recreate: true
        path: ${{ runner.temp }}/code-coverage-results-${{ inputs.comment-header }}.md
